# .github/workflows/deploy.yaml
name: Deploy to Cloud Run

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        token_format: "id_token"
        workload_identity_provider: "projects/293653495816/locations/global/workloadIdentityPools/github/providers/my-repo"
        service_account: "github-deployer@restaurant-rag.iam.gserviceaccount.com"

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v1

    - name: Build and Push Docker image
      run: |
        gcloud builds submit --tag asia-east1-docker.pkg.dev/restaurant-rag/rag-repo/basic-api

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy basic-api \
          --image=asia-east1-docker.pkg.dev/restaurant-rag/rag-repo/basic-api \
          --platform=managed \
          --region=asia-east1 \
          --allow-unauthenticated
