name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches:
      - "main"

env:
  PROJECT_ID: 'restaurant-rag'
  REGION: 'asia-east1'
  ARTIFACT_REGISTRY_NAME: 'rag-repo'
  PROJECT_NAME: 'basic-api'
  SERVICE_ACCOUNT: 'github-deployer@restaurant-rag.iam.gserviceaccount.com'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/293653495816/locations/global/workloadIdentityPools/github/providers/my-repo'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
          create_credentials_file: true

      - name: 'Set up gcloud SDK'
        uses: google-github-actions/setup-gcloud@v2

      - name: 'Configure Docker for Artifact Registry'
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: 'Build and Push Docker image'
        run: |
          IMAGE="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_NAME }}/${{ env.PROJECT_NAME }}:${{ github.sha }}"
          docker build -t "$IMAGE" .
          docker push "$IMAGE"

      - name: 'Deploy to Cloud Run'
        run: |
          IMAGE="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_NAME }}/${{ env.PROJECT_NAME }}:${{ github.sha }}"
          gcloud run deploy ${{ env.PROJECT_NAME }} \
            --image="$IMAGE" \
            --platform=managed \
            --region=${{ env.REGION }} \
            --allow-unauthenticated
